name: Publish Docker image
on:
  push:
    branches:
    - main
jobs:
  build:
    strategy:
      matrix:
        include:
        - node_version: 14
          full_node_version: v14.21.0
          terraform_version: 1.3.3
          terragrunt_version: 0.39.2
        - node_version: 16
          full_node_version: v16.18.0
          terraform_version: 1.3.3
          terragrunt_version: 0.39.2
        - node_version: 18
          full_node_version: v18.12.0
          terraform_version: 1.3.3
          terragrunt_version: 0.39.2
        - node_version: 20
          full_node_version: v20.9.0
          terraform_version: 1.3.3
          terragrunt_version: 0.39.2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install --frozen-lockfile
    - run: sh ./scripts/download.sh files/node-linux-x64-musl.tar.gz https://unofficial-builds.nodejs.org/download/release/${{ matrix.full_node_version }}/node-${{ matrix.full_node_version }}-linux-x64-musl.tar.gz
    - run: sh ./scripts/download.sh files/terraform_linux_amd64.zip https://releases.hashicorp.com/terraform/${{ matrix.terraform_version }}/terraform_${{ matrix.terraform_version }}_linux_amd64.zip
    - run: sh ./scripts/download.sh files/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${{ matrix.terragrunt_version }}/terragrunt_linux_amd64
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        build-args: |
          NODE_VERSION=${{ matrix.node_version }}
          FULL_NODE_VERSION=${{ matrix.full_node_version }}
          TERRAFORM_VERSION=${{ matrix.terraform_version }}
          TERRAGRUNT_VERSION=${{ matrix.terragrunt_version }}
          PULUMI_VERSION=test
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nodejs_devops:${{ matrix.node_version }}
