name: Build & Test
on:
  push:
    branches:
    - init-docker-image
jobs:
  build:
    strategy:
      matrix:
        # node_version: [ 14, 16, 18 ]
        node_version: [ 18 ]
      include:
      - node_version: 14
        full_node_version: v14.21.0
      - node_version: 16
        full_node_version: v16.18.0
      - node_version: 18
        full_node_version: v18.12.0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install --frozen-lockfile
    - run: sh ./scripts/download.sh node-linux-x64-musl.tar.gz https://unofficial-builds.nodejs.org/download/release/${full_node_version}/node-${full_node_version}-linux-x64-musl.tar.gz
    - run: sh ./scripts/download.sh terraform_linux_amd64.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      env:
        TERRAFORM_VERSION: 1.3.3
    - run: sh ./scripts/download.sh terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
      env:
        TERRAGRUNT_VERSION: 0.39.2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2
#    - name: Build and push
#      uses: docker/build-push-action@v3
#      with:
#        context: .
#        file: ./Dockerfile
#        push: true
#        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/node_dind:latest
